### ISSUE TITLE
Live demo not working well in Chrome

### ISSUE THREAD

**Issue by DemersM** [Esri/participatory-planning#10]
Hi,

I was looking at your demo in Chrome and the VectorTiles are not showing up and when you trace buildings, you dont see the vertices.

I am using Chrome 86.0.4240.111 (official Build) (64 bits)

In Firefox everything work correctly.

**Comment by arnofiva** [comment]
Hi @DemersM, thanks for trying out the app and sorry to hear you ran into problems. Did you run the demo from the source code or using the live version at https://esri.github.io/participatory-planning/?

The live version works for me using the same version of Chrome on MacOS. It's possible that the VectorTiles not showing up was related to a server hick-up.

I also quickly tried creating some buildings which seemed to work as expected. Would be great if you could give it another try or provide more specifics. Thanks!

<img width="1141" alt="Screen Shot 2020-10-26 at 4 32 31 PM" src="https://user-images.githubusercontent.com/4146006/97193088-e478d200-17a8-11eb-8090-6ffcf6d5affe.png">
