### ISSUE TITLE
app stopped working

### ISSUE THREAD

**Issue by chjch** [Esri/participatory-planning#44]
I tried using the live demo and build from the source using npm. However, neither of the approaches is working. Both buttons: "start planning' and "skip animation" have no effect.
<img width="1280" alt="image" src="https://github.com/Esri/participatory-planning/assets/12037254/36d98e84-30bf-4a10-91b3-abe58e02ddd7">

**Comment by arnofiva** [comment]
Thanks for letting us know, looks like one of the CDN dependencies is missing. We'll look into it asap!

**Comment by sciandfi** [comment]
I am also facing the same issue now. Are you sure this problem has been resolved?

**Comment by arnofiva** [comment]
@sciandfi we just finished upgrading the source code to latest ArcGIS Maps SDK for JavaScript other dependencies. We also changed the build setup quite a bit, can you try again please?
